// "DRIVER 0 STEP1:"
//  [ { name: 'ACSC CEDAR ES 02 PM (M,T,W,Th,F)',
//     status: '',
//     mdd: '',
//     ampm: 'AM',
//     days: '(M, T, W, Th, F)',
//     monitor: false,
//     passangers: 'Naomi Oates-Smith',
//     state: 'Indiana',
//     city: '',
//     pickUp: Sat Dec 30 1899 07:30:00 GMT-0500 (Eastern Standard Time),
//     dropOff: Sat Dec 30 1899 08:25:00 GMT-0500 (Eastern Standard Time),
//     address: 
//      [ '9515 Pendleton Pike, Indianapolis, IN 46236',
//        '685 S Avon Ave, Avon, IN 46123' ] },
//   { name: 'ACSC CEDAR ES 02 PM (M,T,W,Th,F)',
//     status: '',
//     mdd: '',
//     ampm: 'PM',
//     days: '(M, T, W, Th, F)',
//     monitor: false,
//     passangers: 'Naomi Oates-Smith',
//     state: 'Indiana',
//     city: '',
//     pickUp: Sat Dec 30 1899 15:10:00 GMT-0500 (Eastern Standard Time),
//     dropOff: Sat Dec 30 1899 16:03:00 GMT-0500 (Eastern Standard Time),
//     address: 
//      [ '685 S Avon Ave, Avon, IN 46123',
//        '9515 Pendleton Pike, Indianapolis, IN 46236' ] } ]